name: badger
description: Experimental Programming Language
version: 0.2.0
dependencies:
  analyzer: "^0.27.4"
  args: "^0.13.5"
  crypto: "^2.0.1"
  petitparser: "^1.5.3"
  path: "^1.3.9"
  json_diff: "^0.1.2"
  http_server: "^0.9.6"
  parsejs: ">=1.0.3 <2.0.0"
  dart_style: "^0.2.0"
  stack_trace: "^1.6.6"
executables:
  badger: "badger"
