name: badger
description: Experimental Programming Language
version: 0.1.0
dependencies:
  analyzer:
    git:
      url: https://github.com/dart-lang/ddc_analyzer.git
      ref: 901ecfffe7c29db4ac4db2f8ac90ea790b995895
  args: ">=0.12.0 <0.14.0"
  crypto: ">=0.9.0 <0.10.0"
  petitparser: ">=1.3.7 <2.0.0"
  path: ">=1.3.3 <2.0.0"
  json_diff: ">=0.1.1 <0.2.0"
  http_server: ">=0.9.5+1 <0.10.0"
executables:
  badger: "badger"
